
GET http://localhost:3001/api/persons
###
curl -X POST http://localhost:3001/api/persons \
  -H "Content-Type: application/json" \
  -d '{"name": "Raj Kumar", "number": "9876543210"}'
###
curl -X POST http://localhost:3001/api/persons \
  -H "Content-Type: application/json" \
  -d '{"name": "", "number": ""}'

###
curl -X POST http://localhost:3001/api/persons \
  -H "Content-Type: application/json" \
  -d '{"name": "Arto Hellas", "number": "1234"}'


### Create new person

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "ra",
  "number": "1234"
}

###
DELETE http://localhost:3001/api/persons/687a2ce6aa3f95e73fac6946